"""Publish mapped scores separately; historical strict scores and visual diagnostics stay intact."""
from pathlib import Path
import copy,html,json
P=Path(__file__).resolve().parent;R=P/'results';OLD=P/'../hue-fair-refine'
a=json.loads((R/'colorbench.json').read_text());old=json.loads((OLD/'results/colorbench.json').read_text())
site=copy.deepcopy(json.loads((OLD/'results/site-data.json').read_text()));site['input_policy']='mapped-012-v1';site['benchmark_note']='Original Python ColorBench, mapped bounded import. Historical strict scores remain selectable. No tuning or boundary update.'
lines=['# HRL 0.12: mapped-import ColorBench rerun','','The frozen 0.12 balanced and gentle checkpoints were rerun with ordinary mapped import, alongside the unchanged 0.11 balanced control. No coefficient, hue field, source atlas, physical boundary or valid-address color generation changed. The separate pending 0.13 boundary repair was not included.','','Only the five scored generation and sixteen scored measurement columns were run. The original Python judges and original forwarding helper are unchanged. There is no ellipsoid tensor rescaling or replacement with a local-derivative test. All forwarded inputs yielded finite coordinates; mappings are disclosed instead of dropping those inputs.','','## COMBVD','','Native mapped scores now cover all 3,813 pairs. Their historical strict results cover only 3,331, so those totals are not an optimization comparison. The same 3,331 supported native pairs reproduce their old scores. Full uses all 3,813 without mapping and reproduces its old scores. COMBVD is fitted/in-sample; other datasets have earlier project exposure.','','| Model | Gamut | Weighted STRESS | Unweighted STRESS | Pairs | Mapped pairs | Historical supported-pair weighted STRESS |','|---|---|---:|---:|---:|---:|---:|']
for g in ['srgb','full']:
 for n in ['parent','balanced','gentle']:
  m=a['models'][n+'-'+g];c=m['combvd'];common=m['historical_common_pairs'];label='0.11 balanced control' if n=='parent' else '0.12 '+n
  lines.append(f"| {label} | {g} | {c['traditional_weighted']:.6f} | {c['unweighted']:.6f} | {c['retained']} | {c['mapped_pairs']} | {common['weighted']:.6f} ({common['pairs']} pairs) |")
  dest=site['profiles'][g]['models'][n];dest.update(weighted=c['traditional_weighted'],unweighted=c['unweighted'],pairs=c['retained'],mapped_pairs=c['mapped_pairs'])
  for board in ['generation','measurement']:
   for ds,v in m[board].items():
    u=v['audit'];dest[board][ds]={'score':v['score'],'exact':v['exact_input_support'],'finite':True,'mapped':u['mapped'],'rejected':u['rejected'],'continued':u.get('continued',0),'events':u['event_counts']}
lines+=['','## Previously affected full-gamut tests','','These are input evaluations, not necessarily distinct stimuli. Reason counts can overlap. Upstream-generated skips are not HRL rejections.','','| Test | 0.12 balanced | 0.12 gentle | Mapped / forwarded input evaluations | HRL rejected | Contributing groups |','|---|---:|---:|---:|---:|---|']
for ds in ['hung_berns','brown_1957_12obs_ellipsoids','wyszecki_fielder_1971_ellipsoids','brown_macadam_1949_ellipsoids']:
 board='generation' if ds=='hung_berns' else 'measurement';b=a['models']['balanced-full'][board][ds];c=a['models']['gentle-full'][board][ds];u=b['audit'];details=b['details']
 groups={k:v for k,v in details.items() if k.startswith('n_') or k in ['n','count']}
 lines.append(f"| {ds} | {b['score']:.6f} | {c['score']:.6f} | {u['mapped']}/{u['points']} | {u['rejected']} | {groups} |")
lines+=['','The upstream finite-ellipsoid generator still skips its original invalid centers and clamps negative XYZ before forwarding. That behavior is not changed here. The previous strict one-center Brown score is not a full-population comparison. The pending tensor-scale investigation remains separate; these are original-implementation pipeline scores.','','## Complete scored boards','','All values below are lower-is-better. A dagger means at least one input was mapped, not that the test failed. Mapping counts are per forward evaluation. Full strict-to-mapped differences are policy/population changes, not newly fitted improvements.']
for g in ['srgb','full']:
 for board in ['generation','measurement']:
  lines+=['',f'### {g}: {board}','','| Dataset | 0.12 balanced | 0.12 gentle | Balanced mapped / forwarded | Rejected |','|---|---:|---:|---:|---:|']
  for ds,z in a['models']['balanced-'+g][board].items():
   other=a['models']['gentle-'+g][board][ds];u=z['audit'];mark=' †' if u['mapped'] else ''
   lines.append(f"| {ds} | {z['score']:.6f}{mark} | {other['score']:.6f}{' †' if other['audit']['mapped'] else ''} | {u['mapped']}/{u['points']} | {u['rejected']} |")
lines+=['','## Exact policy','','Use the unchanged 0.12 physical boundary. Adapt declared source white to D65 and normalize absolute luminance to the HRL white. A sourceWhiteNits argument permits different source/target luminance scales. For upstream already-relative D65 test inputs those white luminances match, so there is no extra numerical rescaling or second Bradford adaptation.','','Imaginary input chromaticity is projected radially from D65 in u-prime/v-prime onto the existing boundary, not claimed to be a perceptually nearest point. The relative Y ceiling scales XYZ together, retaining chromaticity. Native sRGB then explicitly clips linear channels into its cube if necessary. Invalid/nonfinite tuples remain programming errors; an unexpected runtime conversion error aborts rather than yielding null/NaN. No additional above-white intensity coordinate is used.','','Clipped input cannot round-trip to the original out-of-range tuple. Already-supported conversions and generated colors are tested bit-identical. The tests verify 1.2 at a 100-nit source as 120 nits, represented at 0.4 relative to 300 nits or clipped to 1 relative to 100 nits. They also test declared-source-white adaptation and nominal P3/Rec.2020 input acceptance. This does not claim a new P3-native gamut profile.','','## Preserved records','','Original strict and previously mapped score files remain at ../hue-fair-refine/results/. The interactive 0.12 comparison loads these new mapped scores by default and provides a historical-strict selector. Its triangle rendering and inherited visual diagnostics are unchanged. Per-input event masks, raw COMBVD arrays, per-family mapping flags, source hashes and versions are retained. No overall leaderboard rank is inferred.','','```json',json.dumps({'colorbench':a['colorbench_commit'],'pool':a['pool_commit'],'scoredCells':a['completed_scored_cells'],'failedForwardRows':a['failed_forward_rows'],'frozenSourcesUnchanged':a['frozen_sources_unchanged']},indent=2),'```','']
(R/'REPORT.md').write_text('\n'.join(lines));(R/'site-data.json').write_text(json.dumps(site,indent=2)+'\n')
parts=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HRL 0.12 mapped ColorBench</title><link rel="stylesheet" href="../../hue-fair-ui/style.css"><main><nav><a href="../../hue-fair.html">0.12 comparison</a><a href="results/REPORT.md">Report</a><a href="results/colorbench.json">Raw results</a><a href="results/scores.csv">CSV</a></nav><h1>0.12: mapped-import ColorBench</h1><p>Unchanged checkpoints, original Python judges, ordinary bounded import. All supplied inputs converted; mappings remain disclosed. No tuning or boundary upgrade.</p>']
for g in ['srgb','full']:
 parts.append('<h2>'+html.escape(g)+'</h2><p>All 3,813 COMBVD pairs. Original native strict scores used 3,331.</p>')
 for board in ['generation','measurement']:
  parts.append('<h3>'+board+'</h3><div class="scroll"><table><tr><th>Test</th><th>Balanced</th><th>Gentle</th><th>Mapped / inputs</th></tr>')
  for ds,z in a['models']['balanced-'+g][board].items():
   u=z['audit'];other=a['models']['gentle-'+g][board][ds];parts.append(f'<tr><td>{html.escape(ds)}</td><td>{z["score"]:.6f}</td><td>{other["score"]:.6f}</td><td>{u["mapped"]}/{u["points"]}</td></tr>')
  parts.append('</table></div>')
parts.append('<footer>Mapping is part of the evaluated pipeline, not new perceptual fitting. Raw support and contributing-group information are in the report.</footer></main></html>');(P/'index.html').write_text('\n'.join(parts))
print('Generated mapped report, score page and comparison evidence without altering old results')
