import {createHRLv2} from './index.mjs';
import {createContourHRL} from './research/level-contours/index.mjs';
import {genRuler} from './research/tonal-semantics/ruler.mjs';
import {XYZ_TO_SRGB,mul3,encodeSRGB} from './lib/srgb-triangles.mjs';
import {canonicalScale} from './codes.mjs';
const names={beta1:'Beta 1',strict:'Contour first',metric:'Metric compromise',seed:'Unfitted base',guarded:'Ordering penalty'};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function display(x,mask,i){const v=mul3(XYZ_TO_SRGB,x),clipped=v.some(x=>x< -2e-9||x>1+2e-9),rgb=v.map(x=>Math.round(255*encodeSRGB(clamp(x,0,1))));return mask&&clipped&&i%13<3?rgb.map((v,j)=>Math.round(.4*v+.6*[248,164,212][j])):rgb;}
function turn(a){return Math.max(0,(a.slice(1).reduce((s,x,i)=>s+Math.abs(x-a[i]),0)-Math.abs(a.at(-1)-a[0]))/2);}
export function renderContour(model,H,L,zoom,mask=false){
 const width=201,height=233,pixels=new Uint8ClampedArray(width*height*4);
 for(let y=0;y<height;y++)for(let x=0;x<width;x++){const R=x/(width-1),l=1-y/(height-1)+R/2;if(R>l||l>1)continue;pixels.set([...display(model.toXYZ({H,R,L:l}),mask,x+y),255],4*(y*width+x));}
 const strip=new Uint8ClampedArray(513*24*4),J=[];
 for(let i=0;i<513;i++){const xyz=model.toXYZ({H,R:L*zoom*i/512,L}),rgb=display(xyz,mask,i);J.push(genRuler(xyz)[0]);for(let y=0;y<24;y++)strip.set([...rgb,255],4*(y*513+i));}
 return{width,height,pixels,strip,J,turn:turn(J)};
}
function worker(){const models=new Map();let pending=null,busy=false;
 async function get(g,id){const k=g+id;if(!models.has(k))models.set(k,(id==='beta1'?createHRLv2({gamut:g}):createContourHRL({gamut:g,checkpoint:id})).catch(e=>{models.delete(k);throw e;}));return models.get(k);}
 async function run(){if(busy)return;busy=true;while(pending){const job=pending;pending=null;try{const views={};for(const slot of ['beta1','candidate']){const m=await get(job.gamut,slot==='beta1'?'beta1':job.candidate);if(pending)break;views[slot]=renderContour(m,job.H,job.L,job.zoom,job.mask);}if(!pending)self.postMessage({id:job.id,views});}catch(e){self.postMessage({id:job.id,error:e.message});}await new Promise(r=>setTimeout(r,0));}busy=false;}
 self.onmessage=({data})=>{pending=data;run();};
}
function page(){
 const $=id=>document.getElementById(id),state={gamut:'srgb',candidate:'strict',H:300,L:.08,zoom:.25,mask:false};let engine,request=0,results=null,timer;
 const params=new URLSearchParams(location.hash.slice(1));for(const k of ['gamut','candidate'])if((k==='gamut'?['srgb','full']:['strict','metric','guarded','seed']).includes(params.get(k)))state[k]=params.get(k);
 for(const k of ['H','L','zoom'])if(params.has(k)&&Number.isFinite(+params.get(k)))state[k]=+params.get(k);state.H=((state.H%360)+360)%360;state.L=clamp(state.L,.00001,1);state.zoom=state.zoom===1?1:.25;
 function paint(id,p,w,h){const c=$(id);c.width=w;c.height=h;c.getContext('2d').putImageData(new ImageData(p,w,h),0,0);}
 function table(){if(!results)return;const g=state.gamut;$('table-caption').textContent=g==='srgb'?'Native sRGB · 3,331 retained pairs':'Full · 3,813 retained pairs';$('results').replaceChildren();for(const id of ['beta1','strict','metric','guarded','seed']){const r=results.models[id]?.[g];if(!r)continue;const tr=document.createElement('tr');for(const value of [names[id],r.score.weighted.toFixed(4),r.score.mappedAll?r.score.mappedAll.weighted.toFixed(4):'—',`${r.nearGray.overThreshold} / ${r.nearGray.paths}`,r.nearGray.meanTurn.toFixed(6),r.levelOrdering.worstDrop.toFixed(5)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('results').append(tr);}$('results-note').textContent='Counts refer to fixed-Level lightness turns near gray. The final column reports the worst lightness drop as Level increases at fixed Reach, across 32,256 sampled steps. Full-domain ordering remains unresolved. No new ColorBench run or held-out score is claimed.';}
 function sync(){const max=canonicalScale(state.gamut).maximum;$('gamut').value=state.gamut;$('candidate').value=state.candidate;$('hue').value=state.H;$('level').max=max;$('level').value=(state.L*max).toFixed(2);$('level-range').textContent=`0–${max}`;$('zoom').value=String(state.zoom);$('candidate-title').textContent=names[state.candidate];$('legend-candidate').textContent=names[state.candidate];$('display-note').textContent=state.gamut==='srgb'?'Native sRGB is displayed directly. Curves use XYZ before display clipping.':'Full-domain colors are clipped to this sRGB display. Curves use the original XYZ; turn on the clipping marks to see affected areas.';$('curve-range').textContent=`H ${state.H}° · Level ${(state.L*max).toFixed(2)} · Reach 0–${(state.L*state.zoom*max).toFixed(2)}`;for(const e of document.querySelectorAll('.strip-label'))e.textContent=`Fixed Level ${(state.L*max).toFixed(2)} · Reach 0–${(state.L*state.zoom*max).toFixed(2)}`;}
 function render(){sync();table();const p=new URLSearchParams({gamut:state.gamut,candidate:state.candidate,H:state.H,L:state.L,zoom:state.zoom});history.replaceState(null,'','#'+p);$('status').textContent='Evaluating the selected contours…';$('retry').hidden=true;document.querySelector('.sheets').setAttribute('aria-busy','true');engine.postMessage({...state,id:++request});}
 function start(){engine?.terminate();engine=new Worker(new URL('./contours.mjs',import.meta.url),{type:'module'});engine.onerror=()=>error('The color worker failed. Retry to reload it.');engine.onmessage=({data})=>{if(data.id!==request)return;if(data.error)return error(data.error);const all=Object.values(data.views).flatMap(v=>v.J),lo=Math.min(...all),hi=Math.max(...all),pad=Math.max(.002,(hi-lo)*.1),min=lo-pad,max=hi+pad,ns='http://www.w3.org/2000/svg',svg=$('curve');svg.replaceChildren();function elem(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);}for(let i=0;i<=4;i++){const y=20+200*i/4;elem('line',{x1:65,y1:y,x2:810,y2:y,stroke:'#51455d'});elem('text',{x:56,y:y+5,fill:'#b9abc8','text-anchor':'end','font-size':14},(max-(max-min)*i/4).toFixed(3));}for(const slot of ['beta1','candidate']){const v=data.views[slot];paint('triangle-'+slot,v.pixels,v.width,v.height);paint('strip-'+slot,v.strip,513,24);$('turn-'+slot).textContent=`Lightness turn: ${v.turn.toFixed(6)} J`;const points=v.J.map((x,i)=>`${65+745*i/512},${20+200*(max-x)/(max-min)}`).join(' ');elem('polyline',{points,fill:'none',stroke:slot==='beta1'?'#f8a4d4':'#8ce3c7','stroke-width':2.5});}elem('text',{x:65,y:250,fill:'#b9abc8','font-size':14},'Gray · Reach 0');elem('text',{x:810,y:250,fill:'#b9abc8','text-anchor':'end','font-size':14},`Reach ${(state.L*state.zoom*canonicalScale(state.gamut).maximum).toFixed(2)}`);$('status').textContent='Both contours ready.';document.querySelector('.sheets').setAttribute('aria-busy','false');};render();}
 function error(message){$('status').textContent=message;$('retry').hidden=false;document.querySelector('.sheets').setAttribute('aria-busy','false');}
 for(let H=0;H<360;H+=30){const b=document.createElement('button');b.textContent=H+'°';b.addEventListener('click',()=>{state.H=H;render();});$('quick-hues').append(b);}
 for(const k of ['gamut','candidate','zoom'])$(k).addEventListener('change',()=>{state[k]=k==='zoom'?+$(k).value:$(k).value;render();});$('mask').addEventListener('change',()=>{state.mask=$('mask').checked;render();});
 $('hue').addEventListener('change',()=>{if(!Number.isFinite($('hue').valueAsNumber))return sync();state.H=(($('hue').valueAsNumber%360)+360)%360;render();});$('level').addEventListener('change',()=>{if(!Number.isFinite($('level').valueAsNumber))return sync();state.L=clamp($('level').valueAsNumber/canonicalScale(state.gamut).maximum,.00001,1);render();});$('retry').addEventListener('click',start);
 fetch('./research/level-contours/results/comparison.json').then(r=>{if(!r.ok)throw Error('Results unavailable');return r.json();}).then(r=>{results=r;table();}).catch(e=>{$('results-note').textContent=e.message;});start();
}
if(typeof document!=='undefined')page();else if(typeof self!=='undefined')worker();
