/** Offline, self-contained comparison picker. Data are the tested model, not a raster surrogate. */
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),R=root+'/research/anchor-0.7';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const strip=s=>s.replace(/^import .*?;\s*$/gm,'').replace(/export (class|function|const|async function)/g,'$1').replace(/^export \{[^}]*\}(?: from [^;]+)?;\s*$/gm,'');
const mods=[['hue-field.mjs',['HueField','ReleaseRing']],['srgb-triangles.mjs',['SRGBTriangles','SRGB_TO_XYZ','XYZ_TO_SRGB','mul3','decodeSRGB','encodeSRGB']],['basr.mjs',['BASRModel','levelToNonblack','nonblackToLevel']],['index.mjs',['expandReleaseAngles']],['research.mjs',['ResearchSRGBTriangles','SpectralCarrier','EqualSpanFull','AppearanceReadout','MonotoneAtlas','PathModel']],['opal-anchor.mjs',['unitWarp','fitCoordinates','AnchorAppearanceReadout','AnchorModel']]];
const packed=mods.map(([file,names])=>{let s=fs.readFileSync(root+'/lib/'+file,'utf8');if(file==='index.mjs')s=s.split('async function v2Read')[0];if(file==='research.mjs')s=s.split('async function readResearch')[0];if(file==='opal-anchor.mjs')s=s.split('async function read(name)')[0];return`const {${names}}=(()=>{${strip(s)}\nreturn {${names}};})();`;}).join('\n');
const board=read(R+'/results/benchmarks.json');const scores={models:{},matched_3331:board.matched_3331};for(const [k,v]of Object.entries(board.models))scores.models[k]={weighted:v.weighted,unweighted:v.unweighted};
const data={field:read(root+'/data/hue-field-0.6.json'),angles:read(root+'/data/release1-angles.json'),readouts:read(root+'/data/appearance-readouts.json'),brightness:read(R+'/results/brightness-readout.json'),scores};
for(const g of ['srgb','full']){data['opal-'+g]=read(root+'/data/opal-'+g+'.json');data['anchor-'+g]=read(R+'/results/anchor-'+g+'.json');for(const n of [3,6,12]){const f=read(R+`/results/fit-${g}-g${n}.json`);data[`fit-${g}-${n}`]={harmonics:f.harmonics,coefficients:f.coefficients,geometry_weight:f.geometry_weight};}}
const t=fs.readFileSync(root+'/source/opal-anchor-template.html','utf8');const html=t.replace('__RUNTIME__',packed).replace('__DATA__',JSON.stringify(data).replaceAll('</','<\\/'));fs.writeFileSync(root+'/opal-anchor.html',html);console.log('OPAL 0.7 viewer bytes',Buffer.byteLength(html));
