/** Human-readable tables generated from the actual JavaScript score receipt. */
import fs from 'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),r=JSON.parse(fs.readFileSync(root+'/results/benchmarks.json','utf8')),f=x=>x.toFixed(4);
let s='# OPAL 0.7 COMBVD and reference diagnostics\n\nAll 0.7 fitted scores are development / in-sample results. Lower STRESS is better. The shared input, exact masks, nuisance scales and rejected rows are in `results/benchmarks.json`. Quantization and channel clipping are absent. The metric is the public regular bicone.\n\n',csv=['gamut,subset,n,OPAL06,balanced07,metric07,conservative07'];
for(const g of ['srgb','full']){
 s+=`## ${g==='srgb'?'Native sRGB':'Full-domain'}\n\n| Subset | Pairs | OPAL 0.6 | Balanced 0.7 | Metric 0.7 | Conservative 0.7 |\n|---|---:|---:|---:|---:|---:|\n`;
 for(const [ds,z]of Object.entries(r.models['balanced-'+g].subsets)){const vals=['opal0.6','balanced','metric','conservative'].map(v=>f(r.models[v+'-'+g].subsets[ds].stress));s+=`| ${ds} | ${z.n} | ${vals.join(' | ')} |\n`;csv.push([g,ds,z.n,...vals].join(','));}
 for(const [key,name]of [['unweighted','Pooled unweighted'],['weighted','Pooled traditional weights']]){const vals=['opal0.6','balanced','metric','conservative'].map(v=>f(r.models[v+'-'+g][key].stress));s+=`| **${name}** | **${r.models['balanced-'+g][key].n}** | **${vals.join('** | **')}** |\n`;csv.push([g,name,r.models['balanced-'+g][key].n,...vals].join(','));}
 s+='\n';
}
s+='## Identical 3,331-pair mask\n\n| Model | Native sRGB | Full-domain on the same pairs |\n|---|---:|---:|\n';for(const v of ['opal0.6','anchor-control','balanced','metric','conservative'])s+=`| ${v} | ${f(r.matched_3331[v+'-srgb'].stress)} | ${f(r.matched_3331[v+'-full'].stress)} |\n`;
s+='\n## Whole-family omission diagnostic\n\nEach run omits the named family from the direct difference loss, refits from zero, and scores that omitted family. Appearance constraints, the fixed architecture and OPAL visual reference remain shared. These are retrospective transfer checks, not untouched independent tests.\n\n| Family | sRGB balanced omission | Full balanced omission | sRGB metric omission | Full metric omission |\n|---|---:|---:|---:|---:|\n';for(const ds of ['BFD-P','LEEDS','RIT-DuPont','WITT'])s+=`| ${ds} | ${[6,3].flatMap(n=>['srgb','full'].map(g=>f(r.family_omissions[g+'-g'+n+'-'+ds].omitted_fit.stress))).join(' | ')} |\n`;
s+='\n## Attribution of the improvement\n\nOwn-anchor normalization alone, with the original readout, scored 56.3198 / 46.7465 (native/full). Own-anchor normalization with the new Nayatani/Corney readout but without the final difference fit scores '+f(r.models['anchor-control-srgb'].weighted.stress)+' / '+f(r.models['anchor-control-full'].weighted.stress)+'. The major gain is therefore after joint native R/L difference calibration, not evidence that normalization alone fixes COMBVD.\n\nHue membership, angular allocation and the physical hue sheet remain unchanged from OPAL 0.6. These results do not improve its constant-hue residuals; they improve placement inside the same sheets.\n';
fs.writeFileSync(root+'/BENCHMARKS.md',s);fs.writeFileSync(root+'/results/benchmark-summary.csv',csv.join('\n')+'\n');console.log('Report generated.');
