/** Direct-runtime five-model hue sheets, with no pre-rendered image dependency.
 * Example: node v2/research/conditional-hue/contact-panels.mjs --gamut srgb --out NEW-DIRECTORY
 */
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHRLv2} from '../../index.mjs';
import {createJointHRL} from '../joint-contours/index.mjs';
import {createConditionalFieldHRL} from '../conditional-field/index.mjs';
import {createConditionalHueHRL} from './index.mjs';
import {renderSheet,encodePNG} from '../fresh-field/visuals.mjs';

const option={gamut:'srgb',hues:'117.5,120,122.5,182.5,270,273,275,280',width:'121',height:'141'};
for(let i=2;i<process.argv.length;i++){
  const a=process.argv[i],v=process.argv[++i];if(!['--out','--gamut','--hues','--width','--height','--v3-record','--coupled-record','--contact-record'].includes(a)||!v)throw Error('Use --out NEW-DIRECTORY [--gamut srgb|full] [--hues 120,273] [--width 121 --height 141]');option[a.slice(2).replaceAll('-','_')]=v;
}
if(!option.out)throw Error('Missing --out NEW-DIRECTORY');const gamut=option.gamut,hues=option.hues.split(',').map(Number),width=Number(option.width),height=Number(option.height),out=path.resolve(option.out);
if(!['srgb','full'].includes(gamut)||!hues.length||!hues.every(H=>Number.isFinite(H)&&H>=0&&H<360)||!Number.isInteger(width)||!Number.isInteger(height)||width<3||height<3||height%2!==1)throw Error('Invalid gamut, hues, width or height');
if(fs.existsSync(out))throw Error('Refusing to overwrite '+out);
const shabuf=b=>crypto.createHash('sha256').update(b).digest('hex');
const urls={beta:new URL('../boundary-tonal/results/metric.json',import.meta.url),joint:new URL('../joint-contours/results/joint.json',import.meta.url),v3:new URL('../conditional-field/results/conditional-joint-guarded-v0.json',import.meta.url),coupled:new URL('./results/conditional-hue-coupled-guarded-v0.json',import.meta.url),contact:new URL('./results/conditional-hue-blue-yellow-contact-v0.json',import.meta.url)};
for(const name of ['v3','coupled','contact'])if(option[`${name}_record`])urls[name]=pathToFileURL(path.resolve(option[`${name}_record`]));
const records=Object.fromEntries(Object.entries(urls).map(([name,url])=>{const raw=fs.readFileSync(url);return[name,{sha256:shabuf(raw),record:JSON.parse(raw)}]}));
const [beta,joint,v3,coupled,contact]=await Promise.all([createHRLv2({gamut}),createJointHRL({gamut}),createConditionalFieldHRL({gamut,record:records.v3.record}),createConditionalHueHRL({gamut,record:records.coupled.record}),createConditionalHueHRL({gamut,record:records.contact.record})]);
const columns=[['Beta 1',beta],['Frozen joint',joint],['V3 guarded',v3],['V4 coupled guarded',coupled],['V4 contact FAILED COMBVD',contact]];
fs.mkdirSync(out);
const sources={script:import.meta.url,beta1:new URL('../../index.mjs',import.meta.url),joint:new URL('../joint-contours/index.mjs',import.meta.url),conditionalFieldFactory:new URL('../conditional-field/index.mjs',import.meta.url),conditionalFieldModel:new URL('../conditional-field/model.mjs',import.meta.url),conditionalHueFactory:new URL('./index.mjs',import.meta.url),conditionalHueModel:new URL('./model.mjs',import.meta.url),renderer:new URL('../fresh-field/visuals.mjs',import.meta.url)};
const identity=Object.fromEntries(Object.entries(sources).map(([name,url])=>[name,shabuf(fs.readFileSync(fileURLToPath(url)))]));
const meta={schema:'hrl-v4-contact-five-model-direct-runtime-v1',gamut,width,height,hues,referenceWhiteNits:300,display:'XYZ to sRGB, out-of-range channels clamped only for display',sourceSHA256:identity,recordSHA256:Object.fromEntries(Object.entries(records).map(([name,item])=>[name,item.sha256])),panels:[]};
for(const H of hues)for(const [label,model] of columns){const rendered=renderSheet(model,H,{width,height}),data=encodePNG(rendered),file=`h${String(H).replace('.','p')}-${label.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.png`;
  fs.writeFileSync(path.join(out,file),data);meta.panels.push({requestedH:H,label,renderedH:H,validPixels:rendered.valid,displayClippedPixels:rendered.clipped,file,sha256:shabuf(data),recordSHA256:label==='Beta 1'?records.beta.sha256:label==='Frozen joint'?records.joint.sha256:label==='V3 guarded'?records.v3.sha256:label==='V4 coupled guarded'?records.coupled.sha256:records.contact.sha256});console.log(gamut,H,label,rendered.clipped+'/'+rendered.valid);}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HRL v4 contact comparison ${gamut}</title><style>body{font:16px/1.45 system-ui;margin:2rem;background:#211a29;color:#f2e9fb}a{color:#91e9cc}section{margin:2rem 0}h2{border-bottom:1px solid #674b71}.grid{display:grid;grid-template-columns:repeat(5,minmax(200px,1fr));gap:.8rem}figure{margin:0;min-width:0}img{width:100%;max-width:242px;background:#211a29}figcaption{font-size:.85rem;max-width:25ch}small{color:#f5b4b6}p{max-width:85ch}</style></head><body><h1>Five-model ${gamut} comparison at matched public HRL coordinates</h1><p>Beta 1, frozen joint, v3 guarded, v4 coupled guarded and v4 contact are called at the same public H, Reach R and Level L. The contact fit is a failed COMBVD experiment. Display clipping is reported per panel; full-gamut differences must be evaluated numerically from original XYZ. H182.5 is an adjacent control outside the yellow/blue contact targets. <a href="manifest.json">Record and source hashes</a> · <a href="method.html">Methods and limits</a></p>${hues.map(H=>`<section><h2>Public H ${H}°</h2><div class="grid">${meta.panels.filter(p=>p.requestedH===H).map(p=>`<figure><img src="${esc(p.file)}" alt="${esc(p.label)} whole hue triangle at public H ${H} degrees"><figcaption>${esc(p.label)}<br><small>Clipped ${p.displayClippedPixels.toLocaleString()}/${p.validPixels.toLocaleString()}</small></figcaption></figure>`).join('')}</div></section>`).join('')}</body></html>`;
const method=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V4 contact panel method</title><style>body{font:16px/1.55 system-ui;background:#211a29;color:#f2e9fb;max-width:80ch;margin:2rem auto;padding:0 1rem}a{color:#91e9cc}</style></head><body><h1>V4 contact comparison method</h1><p><a href="index.html">See ${meta.panels.length} panels</a> · <a href="manifest.json">Model hashes and panel SHA-256</a></p><p>Each ${gamut} panel samples identical public HRL coordinates with R = x/(width − 1), L = 1 − y/(height − 1) + R/2, only where 0 ≤ R ≤ L ≤ 1. For each model, actual toXYZ output is converted to display sRGB. Linear sRGB channels outside [0,1] are counted before clipping for display. The model records are identical across native and full realizations; model source identities and immutable record hashes are in manifest.json. H117.5/122.5 and H270/275/280 are neighboring, untrained contact check angles; H182.5 is a control. Do not infer full-gamut properties from its clipped RGB image. COMBVD and numerical physical saturation/luminance checks are separate.</p><p>V4 coupled/contact records were fitted by the capacity team. A brighter yellow and stronger low-Reach blue in a sheet do not establish an overall improvement: both v4 banks remain exploratory and their retained COMBVD is worse than release baselines. These discrete samples do not certify all hues or the continuous Reach–Level domain.</p></body></html>`;
fs.writeFileSync(path.join(out,'index.html'),html);fs.writeFileSync(path.join(out,'method.html'),method);fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(meta,null,2)+'\n');console.log('Wrote',out,meta.panels.length,'panels');
