"""Separated retained-pair development and original mapped ColorBench reports."""
from pathlib import Path
import json,csv,hashlib,numpy as np
P=Path(__file__).resolve().parent;R=P/'results'
load=lambda n:json.loads((R/n).read_text())
b=load('colorbench.json');d=load('direct-final.json');s=load('sheet-final.json');c=load('conditioning-same-grid.json');v=load('verification.json');geo=load('boundary-verification.json');sel=load('SELECTION.json')
ids=['parent','boundary','balanced','metric'];names=['0.12 balanced','Boundary only','Refined balanced','Metric-leaning'];families=['black','white','exchange','reach']
lines=['# HRL 0.13: repaired spectral boundary and shared tonal fitting','','## Scope','','This is a boundary repair followed by actual new Reach/Level fitting. The original 0.12 refined balanced model, an unchanged-coefficient boundary-only realization, and two selected shared fits are separately evaluated. Earlier models, pages and results are not overwritten. Ordinary mapped imports remain the default; no extra intensity coordinate is introduced.','','The normal native-sRGB development COMBVD retains the same 3,331 supported pairs without mapping. ColorBench is a separate all-input mapped pipeline. Both are reported explicitly below.','','## Boundary repair','','The unsimplified convex hull contains '+str(geo['vertices'])+' vertices from all 471 CIE 1931 2-degree 1-nm CMF rows (360–830 nm). It includes the purple closure. It is exact for the stated tabulated/piecewise-linear XYZ-CMF convention, not a claim of exact continuous biological spectral sensitivity. The table is the pinned colour-science 0.4.7 copy, with its byte hash preserved. The CIE data-page DOI is 10.25039/CIE.DS.xvudnb9b. Direct retrieval of the CIE CSV was unavailable during input preparation; no claim of a fresh byte comparison with that CSV is made.','','The full source chart is transported at fixed relative Y, u-prime/v-prime direction and boundary-relative radial fraction. This is geometry-only, not a newly fitted hue field. The boundary-only native-sRGB rendering is unchanged. Absolute/source-white scaling, the relative Y ceiling and ordinary imaginary-input mapping remain in place.','','Boundary verification: 471 tabulated directions, 1,410 between-wavelength samples, 4,096 nonnegative mixtures, 4,096 random HRL round-trips, and 2,048 exact 16-bit spectral-carrier round-trips. No added intensity methods. All prescribed luminance and source-white examples pass.','','## Normal retained-pair COMBVD: no gamut mapping','','Traditional weighted and unweighted STRESS, on a fixed pair population. Lower is better. COMBVD is fitted/in-sample. These are the ordinary development scores, not the all-input ColorBench aggregate.','','| Realization | Checkpoint | Weighted STRESS | Unweighted STRESS | Retained pairs | Mapped pairs |','|---|---|---:|---:|---:|---:|']
retained={}
for g in ['srgb','full']:
 retained[g]={}
 for id,name in zip(ids,names):
  z=b['models'][id+'-'+g]['retained_combvd'];retained[g][id]=z
  assert z['mapped_pairs']==0 and z['pairs']==(3331 if g=='srgb' else 3813)
  assert abs(z['weighted']-d['models'][id][g]['scores']['weighted'])<1e-6
  lines.append(f"| {g} | {name} | {z['weighted']:.6f} | {z['unweighted']:.6f} | {z['pairs']} | {z['mapped_pairs']} |")
lines+=['','The native mask is identical for every checkpoint, with SHA256 '+retained['srgb']['parent']['mask_sha256']+'. The prepared XYZ and adaptation convention are unchanged from the preceding 0.12 retained-pair comparisons. Full totals include 482 additional pairs and should not be treated as a same-stimulus gamut comparison.','','## What the new fits constrain','','All fitted R/L coefficients remain in one bank per candidate, shared across gamuts. Hue identity/ring, neutral progression, vertices and the regular bicone geometry are fixed relative to the repaired source chart. No learned gamut identifier or separate native/full parameter bank is introduced.','','The human-data objective is COMBVD. Synthetic terms use the complete frozen HelmLab GenSpace vector for black dilution, white dilution, fixed-Reach neutral exchange and fixed-Level Reach. Whole-sheet derivatives are transformed into equilateral coordinates. A new analytic Jacobian penalty targets extreme coordinate stretching, using the same normalized points regardless of gamut. No Oklab values or scalar lightness power target enter these new losses. The parent dark-side and already-good-hue safeguards are engineering choices, not new observer measurements.','','Initial raw-Hessian/bilinear trials were numerically dominated by tiny near-edge stencils and were not selected. The successful family uses a bounded-influence log1p bending penalty and a bicubic GenSpace training surrogate; final measurements below use the actual inverse, not that surrogate. Recorded aborted runs and memory limits are preserved, not described as completed trials.','','## Actual-inverse path diagnostics','','Every old/new control uses the same '+str(d['hues'])+' hues, offset '+str(d['hueOffset'])+' degrees, and '+str(d['samples'])+' samples on each path. Twenty paths per hue, four models and two gamuts. These are synthetic numerical checks, not observer preference percentages. Two endpoint steps are excluded for CV/jump, not for direction checks. No display clipping in the measurements.','','| Realization | Checkpoint | Black CV | White CV | Neutral-exchange CV | Reach CV |','|---|---|---:|---:|---:|---:|']
for g in ['srgb','full']:
 for id,name in zip(ids,names):
  z=d['models'][id][g]['summaries'];lines.append('| '+g+' | '+name+' | '+' | '.join(f"{z[f]['meanCV']:.6f}" for f in families)+' |')
lines+=['','CV is step-length standard deviation divided by the mean. A lower average does not guarantee that every hue improved.','','### Whole-sheet regularity','','| Realization | Checkpoint | Mean normalized bending | 95th-percentile hue | Blue mean (255–295°) |','|---|---|---:|---:|---:|']
for g in ['srgb','full']:
 for id,name in zip(ids,names):
  z=s['models'][id][g];lines.append(f"| {g} | {name} | {z['mean']:.6f} | {z['p95Hue']:.6f} | {z['blueMean']:.6f} |")
lines+=['','These nine-point stencils evaluate actual XYZ-to-GenSpace outputs, with vector derivatives expressed in x=sqrt(3)R/2 and z=L-R/2. They do not prove perceptual uniformity or a topological fold. Dense previews include adjacent deep-blue hues 263,269,273,275,277,281,285 and 293 degrees.','','### Corner direction and dark-side progress','','| Realization | Checkpoint | White retreat paths | Mean white retreat fraction | At R=L=.25, Gen L / own vivid Gen L |','|---|---|---:|---:|---:|']
for g in ['srgb','full']:
 for id,name in zip(ids,names):
  z=d['models'][id][g];w=z['summaries']['white'];lines.append(f"| {g} | {name} | {w['cornerRetreatPaths']}/{w['totalPaths']} | {w['meanRetreatFraction']:.8f} | {z['edge']['quarterGenLightness']:.6f} |")
lines+=['','The last column is a diagnostic ratio, not the definition of Level. Approaching white need not increase scalar GenSpace lightness. Corner retreats use full 3D distance to the relevant endpoint. Counts and magnitudes are separate, and neither alone establishes perceptual significance.','','## Common-coordinate conditioning','','Identical normalized source H/R/L points for every model, transformed in both input and output to equilateral coordinates. This derivative is not the gamut-dependent XYZ derivative. It is the same learned map in every realization. All sampled determinants are positive, but severe tails remain possible.','','| Checkpoint | Median condition | 95th percentile | 99th percentile | Maximum |','|---|---:|---:|---:|---:|']
for id,name in zip(ids,names):
 z=c['models'][id];lines.append(f"| {name} | {z['median']:.5f} | {z['p95']:.5f} | {z['p99']:.5f} | {z['maximum']:.5f} |")
lines+=['','## ColorBench: original scored tests, mapped import','','The original five generation and sixteen measurement columns are evaluated with unchanged Python judges/helper and unchanged finite-ellipsoid construction. All finite forwarded input tuples convert. † denotes mapping, not rejection. Mapping counts are per evaluation and may repeat a stimulus. Upstream skips and negative-XYZ preprocessing remain upstream, unaltered.','','### All-input mapped COMBVD','','| Realization | Checkpoint | Weighted STRESS | Unweighted STRESS | Pairs | Mapped pairs |','|---|---|---:|---:|---:|---:|']
for g in ['srgb','full']:
 for id,name in zip(ids,names):
  z=b['models'][id+'-'+g]['combvd'];lines.append(f"| {g} | {name} | {z['traditional_weighted']:.6f} | {z['unweighted']:.6f} | {z['retained']} | {z['mapped_pairs']} |")
for g in ['srgb','full']:
 for board in ['generation','measurement']:
  lines+=['',f'### {g}: {board}','','| Test | 0.12 parent | Boundary only | Balanced | Metric |','|---|---:|---:|---:|---:|']
  for key in b['models']['parent-'+g][board]:
   vals=[]
   for id in ids:
    z=b['models'][id+'-'+g][board][key];assert z['audit']['rejected']==0;vals.append(f"{z['score']:.6f}"+(' †' if z['audit']['mapped'] else ''))
   lines.append('| '+key+' | '+' | '.join(vals)+' |')
lines+=['','Scored differences caused by changing the boundary/mapping are not called fitting improvements. The boundary-only control isolates that change. Full raw mapping reasons and per-input event masks are retained. No overall rank is fabricated from these heterogeneous test columns.','','## Numerical verification and provenance','','Actual runtime checks include near-black and ordinary round-trips, exact integer conversions, preserved neutral/vivid/hue labels relative to the corrected geometry, cyclic continuity, shared-bank identity, untrained Adobe RGB transfer and relative 100/300-nit scaling. The normal mapped import tests are separate from the strict geometric coverage tests. Frozen selection preceded this scored run. Prior project evaluation exposure remains disclosed.','','| Candidate | Native max embedding error | Full max embedding error | Untrained A98 RGB error |','|---|---:|---:|---:|']
for id in ['balanced','metric']:
 z=v['models'][id];lines.append(f"| {id} | {z['profiles']['srgb']['maxEmbeddingError']:.6g} | {z['profiles']['full']['maxEmbeddingError']:.6g} | {z['untrainedThirdGamut']['maxLinearRGBError']:.6g} |")
lines+=['','Source-table hash: '+geo['cmfHash']+'.','','ColorBench '+b['colorbench_commit']+'; dataset pool '+b['pool_commit']+'.','','All executed trial logs and intermediate records are preserved in the review package, including explicitly labeled aborted experiments. Original source and decision history are in PLAN.md, DESIGN.md and EXECUTION.md. A local browser result is not a public deployment receipt; public verification is recorded separately.','','```json',json.dumps(sel,indent=2),'```','']
(R/'REPORT.md').write_text('\n'.join(lines)+'\n');(R/'retained-combvd.json').write_text(json.dumps(retained,indent=2)+'\n')
with (R/'retained-combvd.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['gamut','checkpoint','weighted_stress','unweighted_stress','retained_pairs','mapped_pairs','mask_sha256'])
 for g,ms in retained.items():
  for id,z in ms.items():w.writerow([g,id,z['weighted'],z['unweighted'],z['pairs'],z['mapped_pairs'],z['mask_sha256']])
print('Separated retained-pair and mapped ColorBench reports written')
