import {createSharedHRL} from '../shared-rl/source.mjs';
import {addBlack,addWhite,exchangeNeutral,shares} from './operations.mjs';
import {genRuler,GEN_WHITE,pathStats} from './ruler.mjs';
import {XYZ_TO_SRGB,mul3,encodeSRGB} from '../../lib/srgb-triangles.mjs';
const $=id=>document.getElementById(id),ids=['balanced','metric'],cache=new Map(),key='hrl-tonal-preferences-v1';let request=0,data=null,timer;
const state=()=>({gamut:$('gamut').value,H:Number($('hue').value)%360,R:Number($('reach').value),L:Number($('level').value),operation:$('operation').value,amount:Number($('amount').value)});
const fmt=x=>Number.isFinite(x)?x.toFixed(6):'N/A';
const display=x=>{const rgb=mul3(XYZ_TO_SRGB,x);return{outside:rgb.some(v=>v< -2e-9||v>1+2e-9),rgb:rgb.map(v=>Math.round(255*encodeSRGB(Math.min(1,Math.max(0,v)))))};};
const address=(s,f,a)=>f==='black'?addBlack(s,a):f==='white'?addWhite(s,a):exchangeNeutral(s,s.R+(1-s.R)*a-s.L);
$('panels').innerHTML=ids.map(id=>`<article class="panel"><h2>${id==='balanced'?'Shared balanced':'Shared metric-leaning'}</h2><p class="hint">Unchanged 0.10 coefficients</p>${['black','white','exchange'].map((f,i)=>`<div class="operation"><div>${['Add black: start → black','Add white: start → white','Neutral exchange: dark edge → light edge'][i]}</div><canvas width="257" height="36" class="bar" id="${id}-${f}"></canvas><small id="${id}-${f}-stats"></small></div>`).join('')}<div id="${id}-patch" class="selected-patch"></div><pre id="${id}-read" class="readout"></pre><button data-prefer="${id}">Prefer this for the selected operation</button></article>`).join('');
async function models(gamut){if(!cache.has(gamut))cache.set(gamut,Promise.all(ids.map(checkpoint=>createSharedHRL({gamut,checkpoint,overflow:'reject',imaginary:'reject'}))).catch(e=>{cache.delete(gamut);throw e;}));return cache.get(gamut);}
function table(s){if(!data)return;const h=(Math.round(s.H/5)*5)%360;const rows=['black','white'].map(f=>{const v=data.comparison[s.gamut][f].perHue.find(x=>x.H===h);return`<tr><td>${f==='black'?'Black family':'White family'}</td><td>${fmt(v.balancedCV)}</td><td>${fmt(v.metricCV)}</td><td>${fmt(v.balancedJump)}</td><td>${fmt(v.metricJump)}</td></tr>`;});$('hueTable').innerHTML=rows.join('');$('sampleNote').textContent=`Nearest audited hue: ${h}°. Tables compare five standardized paths, not just the currently selected start.`;}
async function render(){const current=++request,s=state();$('status').textContent='Rendering…';$('status').classList.remove('error');$('hueLabel').textContent=s.H+'°';$('amountLabel').textContent=s.amount.toFixed(2);try{const ms=await models(s.gamut);if(current!==request)return;for(let i=0;i<ids.length;i++){const m=ms[i],id=ids[i];for(const f of ['black','white','exchange']){const xyz=Array.from({length:257},(_,j)=>m.toXYZ(address(s,f,j/256))),canvas=$(id+'-'+f),ctx=canvas.getContext('2d'),img=ctx.createImageData(257,36);let clipped=0;for(let x=0;x<257;x++){const v=display(xyz[x]);if(v.outside)clipped++;for(let y=0;y<36;y++){const k=4*(257*y+x);img.data.set([...v.rgb,255],k);}}ctx.putImageData(img,0,0);let label;try{const p=pathStats(xyz);label=`Gen CV ${fmt(p.cv)} · step jump ${fmt(p.meanStepJump)}`;}catch(e){label='GenSpace diagnostic unavailable: '+e.message;}$(id+'-'+f+'-stats').textContent=label+` · ${(100*clipped/257).toFixed(1)}% display clipped`;}
const q=address(s,s.operation,s.amount),xyz=m.toXYZ(q),g=shares(q),v=display(xyz);$(id+'-patch').style.background=`rgb(${v.rgb.join(' ')})`;let extra;try{const p=genRuler(xyz),dW=Math.hypot(...p.map((v,j)=>v-GEN_WHITE[j]));extra=`Gen L ${fmt(p[0])}\nGen distance to white ${fmt(dW)}`;}catch(e){extra=e.message;}$(id+'-read').textContent=`H ${q.H.toFixed(1)}° · R ${fmt(q.R)} · L ${fmt(q.L)}\nK ${fmt(g.K)} · W ${fmt(g.W)}\nXYZ ${xyz.map(fmt).join(', ')}\n${extra}${v.outside?'\nPreview clipped to sRGB':''}`;}
table(s);$('status').textContent=`Ready · ${s.gamut} · GenSpace only · unchanged shared candidates`;}catch(e){$('status').textContent=e.message;$('status').classList.add('error');}}
function schedule(e){let R=Number($('reach').value),L=Number($('level').value);if(!Number.isFinite(R)||!Number.isFinite(L))return;R=Math.max(0,Math.min(1,R));L=Math.max(0,Math.min(1,L));if(R>L){if(e?.target.id==='reach')L=R;else R=L;}$('reach').value=R;$('level').value=L;clearTimeout(timer);timer=setTimeout(render,90);}
for(const id of ['gamut','hue','reach','level','operation','amount'])$(id).addEventListener('input',schedule);
function saved(){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[];}catch{return[];}}
for(const b of document.querySelectorAll('[data-prefer]'))b.onclick=()=>{try{const a=saved();a.push({...state(),preferred:b.dataset.prefer,recordedAt:new Date().toISOString(),interpretation:'Informal visual preference; viewing luminance and calibration unknown'});localStorage.setItem(key,JSON.stringify(a));$('saved').textContent=`${a.length} preferences saved in this browser.`;}catch(e){$('saved').textContent='Storage unavailable: '+e.message;}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:key,observations:saved()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hrl-tonal-preferences.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
fetch('results/genspace-audit.json').then(r=>{if(!r.ok)throw Error('Audit fetch failed '+r.status);return r.json();}).then(x=>{data=x;table(state());}).catch(e=>$('sampleNote').textContent=e.message);
render();
