"""Summarize the GenSpace rerating, keeping the original transforms and data intact."""
from pathlib import Path
import csv,json
P=Path(__file__).resolve().parent;R=P/'results'
a=json.loads((R/'genspace-audit.json').read_text());t=json.loads((R/'operation-tests.json').read_text())
s=['# HRL tonal semantics: GenSpace audit','','## What ran','','The same shared 0.10 balanced and metric candidates were rerated using the repository\'s pinned HelmLab 1.0.0 GenSpace forward transform (neutral correction disabled). This is **not a new colour-space fit**. No Oklab value enters these new diagnostics. Historical coefficients and ColorBench results were not changed or relabeled.','','72 hues, five start ratios, 129 samples per path, two families, two candidates, two gamuts: **371,520 evaluated XYZ samples**, including repeated endpoints. All sampled paths had full numerical GenSpace domain support; no display clipping was used in the analysis. This is not proof of perceptual validity throughout the full physical solid.','','Black family: black → upper-edge tint, reversing addBlack. White family: black-vivid shade → white, using addWhite. R/L share dilution is the proposed operation contract. Fixed-Reach Level is neutral exchange and is not the same as general white dilution. See [DEFINITIONS.md](../DEFINITIONS.md).','','## Full-path step statistics','','CV is step-size standard deviation divided by its mean. Step jump is the absolute difference of adjacent step lengths divided by their mean. Two endpoint steps are trimmed at each end for these statistics. Both use full 3D GenSpace distance; lower means more even by this ruler, not more preferred by a human.','','| Gamut | Candidate | Black-family CV | White-family CV | Black-family step jump | White-family step jump |','|---|---|---:|---:|---:|---:|']
for g in ['srgb','full']:
 for v in ['balanced','metric']:
  m=a['models'][g+'-'+v]['summaries'];b,w=m['black'],m['white'];s.append(f"| {g} | {v} | {b['meanCV']:.6f} | {w['meanCV']:.6f} | {b['meanStepJump']:.6f} | {w['meanStepJump']:.6f} |")
s+=['','## Hue-specific differences','','Each hue compares the mean over five start ratios. Counts are out of 72 hues; they do not identify Coonie\'s preferences. The user\'s own per-hue choices are separate evidence.','','| Gamut | Family | Balanced lower CV | Metric lower CV | Balanced lower step jump | Metric lower step jump |','|---|---|---:|---:|---:|---:|']
for g in ['srgb','full']:
 for f in ['black','white']:
  c=a['comparison'][g][f];s.append(f"| {g} | {f} | {c['balancedLowerCV']} | {c['metricLowerCV']} | {c['balancedLowerJump']} | {c['metricLowerJump']} |")
with (R/'per-hue.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=['gamut','family','H','balancedCV','metricCV','balancedJump','metricJump']);w.writeheader()
 for g in ['srgb','full']:
  for family,c in a['comparison'][g].items():
   for row in c['perHue']:w.writerow({'gamut':g,'family':family,**row})
s+=['','## Direction and endpoint diagnostics','','For black-origin paths, a corner retreat is a decrease in 3D GenSpace distance from black as the path leaves black. For white-directed paths, it is an increase in distance to white while adding white. Threshold: 1e-8 GenSpace units per step; all steps, not endpoint-trimmed. These are ruler-dependent trajectory diagnostics, not proofs of a topological fold or a perceptual reversal.','','| Gamut | Candidate | Black paths with corner retreat / 360 | White paths with corner retreat / 360 |','|---|---|---:|---:|']
for g in ['srgb','full']:
 for v in ['balanced','metric']:
  d=a['models'][g+'-'+v]['summaries'];s.append(f"| {g} | {v} | {d['black']['pathsWithCornerRetreat']} | {d['white']['pathsWithCornerRetreat']} |")
s+=['','This exposes small local departures that are missed by endpoint and round-trip tests. Their perceptual importance is not established simply by counting them. The raw JSON retains the per-path counts and statistics.','','### Scalar lightness is not whiteness','','The raw audit also records decreases in Gen L, but these are not automatically failures of white addition. On the full vivid boundary, some chromatic endpoints exceed reference white on the Gen L correlate. Moving from them toward white can therefore decrease Gen L without moving away from white in the full 3D ruler.','','| Gamut | Vivid endpoints with Gen L above white / 72 | Minimum vivid Gen L | Maximum vivid Gen L |','|---|---:|---:|---:|']
for g in ['srgb','full']:
 rows=a['models'][g+'-balanced']['rows'];ends=[r['white'][-1] for r in rows];high=sum(e['startLightness']>e['endLightness']+1e-8 for e in ends)
 s.append(f"| {g} | {high} | {min(e['startLightness'] for e in ends):.6f} | {max(e['startLightness'] for e in ends):.6f} |")
s+=['',f"Reference white Gen L is {t['GenSpace']['white'][0]:.12f}. These are model outputs, not measurements that those physical colours actually have that perceived lightness. GenSpace is not being presented as a fully validated appearance model of every high-purity colour.",'','At R=L=.25, mean endpoint-normalized Gen L is '+', '.join(f"{g}/{v}: {a['models'][g+'-'+v]['summaries']['black']['edgeQuarterMean']:.6f}" for g in ['srgb','full'] for v in ['balanced','metric'])+'. These are not directly comparable units to the old Oklab-ruler numbers. No colour became darker merely because the ruler changed.','','## Algebra and source interpretation','','The operator test passed 10,000 seeded random cases for simplex containment, same-endpoint composition, cross-endpoint order, corner-distance contraction and fixed-Reach neutral exchange. Maximum recorded composition error: '+str(t['maxCompositionError'])+'.','','ZCAM Equations 17–19 were implemented as Jz/Cz-input attribute functions, not a full XYZ-to-ZCAM replacement. Ideal neutral white gives Kz=20, Wz=100, Vz=42. This is why raw ZCAM correlates must not be inserted as HRL shares. The conceptual two-distance construction has a separate boundary-normalization issue, derived in the definitions record.','','## Scope and next experiment','','The interactive page makes addBlack, addWhite and neutral exchange visible on both existing candidates and records informal per-hue preferences locally. It does not introduce a new candidate under an old name. The next fit should combine both operation families with GenSpace path diagnostics and separately justified appearance constraints, retaining one common coefficient bank. Simply substituting Gen L into the former arbitrary t^1.08 target would still not define blackness and whiteness.','','Only existing transform outputs and algebraic contracts were evaluated. No new observer training, appearance-board score, COMBVD rerun or overall leaderboard rank is claimed. The earlier development-data exposure and inherited physical-boundary limitations remain.','','## Reproduction','','```sh','node v2/research/tonal-semantics/test.mjs','node v2/research/tonal-semantics/audit.mjs','python v2/research/tonal-semantics/report.py','```','','[Raw audit](genspace-audit.json) · [Per-hue CSV](per-hue.csv) · [Operation tests](operation-tests.json) · [Interactive page](../index.html)','','Source hashes:','','```json',json.dumps(a['sourceHashes'],indent=2),'```','']
(R/'REPORT.md').write_text('\n'.join(s))
print('Wrote report and 288 per-hue comparison rows')
