import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {createHRLv2} from '../../index.mjs';import {createJointHRL,coordinates} from './index.mjs';
import {createContourHRL} from '../level-contours/index.mjs';import {genRuler} from '../tonal-semantics/ruler.mjs';
const P=new URL('./results/',import.meta.url),input=JSON.parse(fs.readFileSync(new URL('../boundary-tonal/results/training-inputs.json',import.meta.url)));
const offgrid=process.argv.includes('--offgrid'),names=process.argv.slice(2).filter(x=>x!=='--offgrid');if(!names.length)throw Error('Explicit frozen records required');
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length;const turn=a=>Math.max(0,(a.slice(1).reduce((s,v,i)=>s+Math.abs(v-a[i]),0)-Math.abs(a.at(-1)-a[0]))/2);
const stress=(ds,dv,w)=>{let dd=0,c=0,vv=0;for(let i=0;i<ds.length;i++){dd+=w[i]*ds[i]**2;c+=w[i]*ds[i]*dv[i];vv+=w[i]*dv[i]**2;}return 100*Math.sqrt(Math.max(0,1-c*c/dd/vv));};
const hs=Array.from({length:72},(_,i)=>i*5+(offgrid?1.25:2.5)),levels=offgrid?[.0075,.015,.03,.06,.1,.16,.25]:[.005,.01,.02,.04,.08,.12,.2],orderR=offgrid?[.0003,.003,.025,.075,.15,.35,.65]:[.0001,.001,.01,.05,.2,.5,.8];
const out={schema:'hrl-joint-direct-audit-v2',hues:hs,levels,orderR,nearU:[0,.25],nearSamples:257,threshold:.001,trainingOnly:true,offgrid,models:{}};
let rng=260920;const random=()=>((rng=(1664525*rng+1013904223)>>>0)/4294967296);
for(const name of names){
 const isJoint=!['beta1','strict','guarded'].includes(name),bytes=isJoint?fs.readFileSync(new URL(name+'.json',P)):null,rec=bytes?JSON.parse(bytes):null;
 out.models[name]={};for(const gamut of ['srgb','full']){
 const m=name==='beta1'?await createHRLv2({gamut}):isJoint?await createJointHRL({gamut,checkpoint:name,record:rec}):await createContourHRL({gamut,checkpoint:name}),beta=await createHRLv2({gamut});
 const idx=gamut==='srgb'?input.native_indices:input.dv.map((_,i)=>i);const ds=idx.map(i=>m.distance(m.fromXYZ(input.xyz1[i]),m.fromXYZ(input.xyz2[i])));const score={pairs:idx.length,weighted:stress(ds,idx.map(i=>input.dv[i]),idx.map(i=>input.w[i])),unweighted:stress(ds,idx.map(i=>input.dv[i]),idx.map(()=>1))};
 if(gamut==='srgb'){const all=input.dv.map((_,i)=>m.distance(m.fromXYZ(input.xyz1[i]),m.fromXYZ(input.xyz2[i])));score.mappedAll={pairs:all.length,weighted:stress(all,input.dv,input.w),unweighted:stress(all,input.dv,input.dv.map(()=>1))};}
 console.log(name,gamut,'observer',JSON.stringify(score));
 const rows=[],whole=[],orderRows=[];let vividError=0,grayXYZChange=0,roundtrip=0,analytic=0,negativeSteps=0,worstDrop=0,yNegative=0,worstYDrop=0,worstLocation=null;
 for(const H of hs){
  for(const L of levels){const vs=Array.from({length:257},(_,i)=>genRuler(m.toXYZ({H,R:L*.25*i/256,L})));const j=vs.map(v=>v[0]);const dd=vs.slice(1).map((v,i)=>v.map((x,k)=>x-vs[i][k]));const norm=mean(dd.map(v=>v.reduce((s,x)=>s+x*x,0)));const rough=norm>1e-20?mean(dd.slice(1).map((v,i)=>v.reduce((s,x,k)=>s+(x-dd[i][k])**2,0)))/norm:0;rows.push({H,L,turn:turn(j),gradientVariation:rough});}
  for(const L of [.02,.08,.2,.5,.8]){const vals=Array.from({length:129},(_,i)=>genRuler(m.toXYZ({H,R:L*i/128,L})));const d=vals.slice(1).map((v,i)=>Math.hypot(...v.map((x,j)=>x-vals[i][j])));whole.push({H,L,turn:turn(vals.map(x=>x[0])),stepCV:Math.sqrt(mean(d.map(x=>(x-mean(d))**2)))/Math.max(1e-15,mean(d)),maxRelativeStepJump:Math.max(...d.slice(1).map((x,i)=>Math.abs(x-d[i])/Math.max(1e-15,(x+d[i])/2)))});}
  for(const R of orderR){const xyz=Array.from({length:65},(_,i)=>m.toXYZ({H,R,L:R+(1-R)*i/64}));const j=xyz.map(x=>genRuler(x)[0]);let totalRetreat=0,totalYRetreat=0;for(let i=1;i<65;i++){totalRetreat+=Math.max(0,j[i-1]-j[i]);totalYRetreat+=Math.max(0,xyz[i-1][1]-xyz[i][1]);if(j[i]<j[i-1]-1e-8){negativeSteps++;if(j[i-1]-j[i]>worstDrop){worstDrop=j[i-1]-j[i];worstLocation={H,R,L:R+(1-R)*(i-1)/64,L2:R+(1-R)*i/64};}}if(xyz[i][1]<xyz[i-1][1]-1e-8){yNegative++;worstYDrop=Math.max(worstYDrop,xyz[i-1][1]-xyz[i][1]);}}orderRows.push({H,R,totalRetreat,totalYRetreat});}
  vividError=Math.max(vividError,...m.vivid(H).map((x,i)=>Math.abs(x-beta.vivid(H)[i])));for(const L of [.005,.02,.08,.2,.5,.8])grayXYZChange=Math.max(grayXYZChange,...m.toXYZ({H,R:0,L}).map((x,i)=>Math.abs(x-beta.toXYZ({H,R:0,L})[i])));
 }
 for(let i=0;i<500;i++){const L=.0001+.9998*random(),q={H:360*random(),R:L*(.0001+.9998*random()),L};roundtrip=Math.max(roundtrip,m.distance(q,m.fromXYZ(m.toXYZ(q))));if(isJoint)analytic=Math.max(analytic,m.distance(q,coordinates(coordinates(q,rec),rec,true)));}
 const critical=[];for(let i=0;i<=80;i++){const H=288+i*.1,R=.2,L=.2,L2=.2125,x=m.toXYZ({H,R,L}),y=m.toXYZ({H,R,L:L2});critical.push({H,drop:genRuler(x)[0]-genRuler(y)[0],YDrop:x[1]-y[1]});}
 assert(vividError<1e-12,'vivid anchors changed');assert(roundtrip<1e-6&&analytic<1e-8,'inverse numerical failure');
 const r={score,nearGray:{paths:rows.length,overThreshold:rows.filter(x=>x.turn>.001).length,meanTurn:mean(rows.map(x=>x.turn)),worstTurn:Math.max(...rows.map(x=>x.turn)),meanGradientVariation:mean(rows.map(x=>x.gradientVariation))},wholeContour:{paths:whole.length,meanTurn:mean(whole.map(x=>x.turn)),meanStepCV:mean(whole.map(x=>x.stepCV)),worstRelativeStepJump:Math.max(...whole.map(x=>x.maxRelativeStepJump))},levelOrdering:{negativeSteps,worstDrop,worstLocation,yNegative,worstYDrop,meanTotalRetreat:mean(orderRows.map(x=>x.totalRetreat)),worstTotalRetreat:Math.max(...orderRows.map(x=>x.totalRetreat)),meanTotalYRetreat:mean(orderRows.map(x=>x.totalYRetreat)),worstTotalYRetreat:Math.max(...orderRows.map(x=>x.totalYRetreat))},criticalViolet:{scope:'H288–296 every.1°, fixed R.2, L.2→.2125',worst:critical.reduce((a,b)=>a.drop>b.drop?a:b)},vividError,grayXYZChange,roundtripEmbedding:roundtrip,analyticRoundtrip:analytic,rows,whole,orderRows,critical};if(bytes)r.recordSHA256=crypto.createHash('sha256').update(bytes).digest('hex');out.models[name][gamut]=r;console.log(name,gamut,JSON.stringify({...r,rows:undefined,whole:undefined,orderRows:undefined,critical:undefined}));fs.writeFileSync(new URL('audit-'+(offgrid?'offgrid-':'')+names.join('-')+'.json',P),JSON.stringify(out,null,2)+'\n');
 }}
console.log('PASS direct anchors/inverses; visual and observer measurements reported independently');
