const $=id=>document.getElementById(id),ids=['parent','boundary','balanced','metric'],names=['0.12 balanced','Boundary only','Refined balanced','Metric-leaning'],families=['black','near','white','reach','level'],labels=['Black → vivid: R = L','Near edge: R = 0.96 L','Add white: shade (.65,.65) → white','Reach at L = .65','Level at R = .15'];
const isBeta1=document.documentElement.dataset.hrlRelease==='beta1';
const state={gamut:'srgb',id:isBeta1?'metric':'balanced',q:{H:275,R:.15,L:.3},mask:false,compare:!isBeta1,neutral:false};let renderID=0,sampleID=0,current=null,evidence=null,timer;
const worker=new Worker(new URL('worker.mjs',import.meta.url),{type:'module'});
$('panels').innerHTML=ids.map((id,i)=>`<article class="panel ${id===state.id?'selected':''}" id="panel-${id}"><header><h2>${names[i]}</h2><button class="select-panel" data-active="${id}">Pick here</button></header><p class="score" id="score-${id}">Loading retained-pair scores…</p><div class="vertex"><span>White</span><span>Vivid →</span></div><div class="canvas-wrap"><canvas class="triangle" id="tri-${id}" width="241" height="279" tabindex="0" aria-label="${names[i]} hue triangle. Arrow keys adjust Reach and Level; hold Shift for larger steps."></canvas><span class="cursor" id="cursor-${id}"></span></div><div class="vertex">Black</div><p class="gamut" id="gamut-${id}"></p><p class="reading" id="reading-${id}"></p>${isBeta1?'<details class="path-rulers"><summary>Inspect tonal paths</summary>':''}${families.map((f,j)=>`<div class="barlabel">${labels[j]}</div><canvas id="${f}-${id}" class="bar" width="257" height="20"></canvas>`).join('')}${isBeta1?'</details>':''}<div class="panel-actions"><button data-png="${id}">Save triangle PNG</button></div></article>`).join('');
function paint(c,im){c.width=im.w;c.height=im.h;c.getContext('2d').putImageData(new ImageData(im.pixels,im.w,im.h),0,0);}
function controls(){ document.documentElement.dataset.compare=String(state.compare);document.body.classList.toggle('neutral-surround',state.neutral);if($('compareProfiles'))$('compareProfiles').checked=state.compare;$('neutralSurround').checked=state.neutral;$('showMask').checked=state.mask;$('hue').value=state.q.H;$('hueNumber').value=state.q.H;$('reach').value=state.q.R;$('level').value=state.q.L;$('gamut').value=state.gamut;$('active').value=state.id;for(const id of ids){$('panel-'+id).classList.toggle('selected',id===state.id);$('cursor-'+id).style.left=(100*state.q.R)+'%';$('cursor-'+id).style.top=(100*(1-state.q.L+state.q.R/2))+'%';}}
function sample(){current=null;$('exportColor').disabled=true;worker.postMessage({type:'sample',request:++sampleID,gamut:state.gamut,id:state.id,q:state.q});}
function render(){for(const id of ids)$('reading-'+id).textContent='Updating hue sheet…';$('status').textContent='Rendering exact model outputs…';worker.postMessage({type:'render',request:++renderID,gamut:state.gamut,H:state.q.H,mask:state.mask,ids:state.compare?[state.id,...ids.filter(id=>id!==state.id)]:[state.id]});sample();}
function setHue(H){if(!Number.isFinite(H))return;state.q.H=((H%360)+360)%360;controls();clearTimeout(timer);timer=setTimeout(render,100);}
function validRL(){let R=Number($('reach').value),L=Number($('level').value);if(!Number.isFinite(R)||!Number.isFinite(L))return;R=Math.max(0,Math.min(1,R));L=Math.max(R,Math.min(1,L));state.q.R=R;state.q.L=L;controls();sample();}
worker.onmessage=({data:d})=>{if(d.type==='error'){$('status').textContent=d.message;$('status').classList.add('error');return;}if(d.type==='panel'&&d.request===renderID){paint($('tri-'+d.id),d.tri);for(const f of families)paint($(f+'-'+d.id),d.bars[f]);$('gamut-'+d.id).textContent=d.tri.clipped?`${(100*d.tri.clipped/d.tri.total).toFixed(1)}% needs display clipping to sRGB.`:'100% of this triangle is inside sRGB.';$('reading-'+d.id).textContent=`H ${d.H.toFixed(2)}° · click this triangle for XYZ.`;}else if(d.type==='rendered'&&d.request===renderID){$('status').textContent=`Ready · ${d.gamut} · repaired boundary and frozen shared fits`;$('status').classList.remove('error');controls();sample();}else if(d.type==='sampled'&&d.request===sampleID&&d.id===state.id&&d.gamut===state.gamut){current=d;$('exportColor').disabled=false;const hex='#'+d.rgb.map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();$('hexValue').textContent=hex;$('swatch').style.background=hex;const linear=d.rgb.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});const luminance=.2126*linear[0]+.7152*linear[1]+.0722*linear[2];$('swatch').style.color=luminance>.179?'#111111':'#ffffff';$('swatchLabel').textContent=names[ids.indexOf(d.id)]+(d.clipped?' · display clipped':'');$('readout').textContent=`H ${d.q.H.toFixed(4)}° · R ${d.q.R.toFixed(7)} · L ${d.q.L.toFixed(7)}\nK ${(1-d.q.L).toFixed(7)} · W ${(d.q.L-d.q.R).toFixed(7)}\nRelative D65 XYZ: ${d.xyz.map(v=>v.toPrecision(10)).join(', ')}\n${d.clipped?'Preview clipped; exported XYZ is unchanged.':'No display clipping.'}`;$('reading-'+d.id).textContent=`H ${d.q.H.toFixed(2)}° · R ${d.q.R.toFixed(5)} · L ${d.q.L.toFixed(5)}\nXYZ ${d.xyz.map(v=>v.toPrecision(6)).join(', ')}`;}else if(d.type==='imported'&&d.request===sampleID&&d.id===state.id&&d.gamut===state.gamut){state.q=d.q;controls();render();}};
$('hue').oninput=e=>setHue(Number(e.target.value));$('hueNumber').onchange=e=>setHue(Number(e.target.value));$('reach').onchange=validRL;$('level').onchange=validRL;
$('gamut').onchange=()=>{state.gamut=$('gamut').value;render();tables();};$('active').onchange=()=>{state.id=$('active').value;controls();render();};$('showMask').onchange=()=>{state.mask=$('showMask').checked;render();};$('neutralSurround').onchange=()=>{state.neutral=$('neutralSurround').checked;controls();};
for(const b of document.querySelectorAll('[data-active]'))b.onclick=()=>{state.id=b.dataset.active;controls();sample();};
for(const id of ids){
 const c=$('tri-'+id);
 const pick=e=>{const rect=c.getBoundingClientRect(),R=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),L=1-(e.clientY-rect.top)/rect.height+R/2;if(e.type==='pointerdown'&&(L<R||L>1))return false;state.id=id;state.q.R=R;state.q.L=Math.max(R,Math.min(1,L));controls();sample();return true;};
 c.onpointerdown=e=>{if(e.button!==0)return;if(pick(e)){c.focus();c.setPointerCapture(e.pointerId);}};
 c.onpointermove=e=>{if(c.hasPointerCapture(e.pointerId))pick(e);};
 c.onpointerup=e=>{if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId);};
 c.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();state.id=id;const step=e.shiftKey?.05:.005;if(e.key==='ArrowLeft')state.q.R=Math.max(0,state.q.R-step);if(e.key==='ArrowRight')state.q.R=Math.min(state.q.L,state.q.R+step);if(e.key==='ArrowUp')state.q.L=Math.min(1,state.q.L+step);if(e.key==='ArrowDown')state.q.L=Math.max(state.q.R,state.q.L-step);controls();sample();};
}
for(const H of [0,30,90,150,210,240,255,263,269,273,275,277,281,285,293,300,330]){const b=document.createElement('button');b.textContent=H+'°';b.onclick=()=>setHue(H);$('quick').appendChild(b);}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('hexInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('importHex').click();});
$('importHex').onclick=()=>{current=null;$('exportColor').disabled=true;worker.postMessage({type:'import',request:++sampleID,gamut:state.gamut,id:state.id,hex:$('hexInput').value});};
$('exportColor').onclick=()=>{if(!current){$('status').textContent='Wait for the current color calculation.';return;}const parent=state.id==='parent',r={profile:parent?'HRL-0.12-hue-fair':'HRL-0.13-boundary-tonal',checkpoint:parent?'balanced':state.id,viewCheckpoint:state.id,gamut:state.gamut,boundary:parent?'legacy-39-vertex':'cie1931-2deg-1nm-linear-cone',referenceWhite:'D65',referenceWhiteNits:300,coordinates:current.q,relativeXYZ:current.xyz,displayRGB:current.rgb.map(v=>v/255),displayClipped:current.clipped,sharedCalibration:true};if(isBeta1&&state.id==='metric'){r.release='HRL v2 Beta 1';r.releaseVersion='2.0.0-beta.1';r.definitionSHA256='92aa2f9647b406239dd52cd22feed61794f3d6ed74a1c33ba9361516cff3bb72';}download('hrl-'+(r.releaseVersion?'v2-beta1':state.id)+'-color.json',JSON.stringify(r,null,2));};
for(const b of document.querySelectorAll('[data-png]'))b.onclick=()=>{const a=document.createElement('a');a.href=$('tri-'+b.dataset.png).toDataURL();a.download=`hrl-${state.gamut}-${b.dataset.png}-${state.q.H}.png`;a.click();};
$('share').onclick=async()=>{const u=new URL(location.href);u.hash=new URLSearchParams({g:state.gamut,h:state.q.H,r:state.q.R,l:state.q.L,c:state.id,compare:state.compare?'1':'0',mask:state.mask?'1':'0',neutral:state.neutral?'1':'0'}).toString();try{await navigator.clipboard.writeText(u.href);$('status').textContent='View link copied.';}catch{$('status').textContent=u.href;}};
const aliases={hung_berns:'Hung–Berns hue',ebner_fairchild:'Ebner–Fairchild hue',xiao:'Xiao unique hues',munsell:'Munsell',osa_uniform_scales:'OSA spacing',bfd:'BFD',leeds:'Leeds',witt:'Witt',rit:'RIT-DuPont',macadam:'MacAdam 1974'};
function table(headers,rows){return '<table><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function tables(){if(!evidence)return;const models=evidence.models,g=state.gamut;
 const rr=ids.map((id,i)=>{const m=models[id+'-'+g],r=m.retained_combvd;$('score-'+id).textContent=`Retained COMBVD ${r.weighted.toFixed(4)} weighted / ${r.unweighted.toFixed(4)} unweighted · ${r.pairs} pairs`;return[names[i],r.weighted.toFixed(6),r.unweighted.toFixed(6),r.pairs];});
 $('retained').innerHTML=table(['Checkpoint','Weighted STRESS','Unweighted STRESS','Retained pairs'],rr);
 $('boundaryNote').textContent=g==='srgb'?'The boundary-only native control is identical to 0.12; any native change in the fitted candidates comes from shared R/L coefficients.':'The boundary-only column isolates geometric transport; the learned candidates share that same repaired boundary.';
 const board=$('board').value,keys=Object.keys(models['parent-'+g][board]);const rows=keys.map(k=>[aliases[k]||k,...ids.map(id=>{const v=models[id+'-'+g][board][k],a=v.audit;return `<span title="Mapped ${a.mapped} / ${a.points}; rejected ${a.rejected}" class="${a.mapped?'support':''}">${v.score.toFixed(6)}${a.mapped?' †':''}</span>`;})]);$('benchTable').innerHTML=table(['Dataset',...names],rows);
 $('mappedCombvd').innerHTML='<h3>ColorBench all-input mapped COMBVD</h3>'+table(['Checkpoint','Weighted STRESS','Unweighted STRESS','Pairs','Mapped pairs'],ids.map((id,i)=>{const c=models[id+'-'+g].combvd;return[names[i],c.traditional_weighted.toFixed(6),c.unweighted.toFixed(6),c.retained,c.mapped_pairs];}));
}
$('board').onchange=tables;
fetch('research/boundary-tonal/results/colorbench.json').then(r=>{if(!r.ok)throw Error('Benchmark evidence unavailable '+r.status);return r.json();}).then(x=>{evidence=x;tables();}).catch(e=>$('retained').textContent=e.message);
function restoreView(){try{const h=new URLSearchParams(location.hash.slice(1));state.compare=h.has('compare')?h.get('compare')==='1':!isBeta1;state.mask=h.get('mask')==='1';state.neutral=h.get('neutral')==='1';if(['srgb','full'].includes(h.get('g')))state.gamut=h.get('g');if(ids.includes(h.get('c')))state.id=h.get('c');if(h.has('h'))state.q.H=((+h.get('h')%360)+360)%360;if(h.has('l'))state.q.L=Math.max(0,Math.min(1,+h.get('l')));if(h.has('r'))state.q.R=Math.max(0,Math.min(state.q.L,+h.get('r')));if(!Object.values(state.q).every(Number.isFinite))state.q={H:275,R:.15,L:.3};}catch{}controls();tables();render();}
window.addEventListener('hashchange',restoreView);restoreView();

if($('compareProfiles'))$('compareProfiles').onchange=e=>{state.compare=e.target.checked;controls();render();};
function workerFailure(){current=null;$('exportColor').disabled=true;$('status').classList.add('error');$('status').textContent='The color engine could not load. Reload this page to try again; the definition and saved benchmark reports remain available.';}
worker.onerror=workerFailure;worker.onmessageerror=workerFailure;
