import {coordinatesFromRGB,PERIMETERS} from './appearance-runtime.mjs';
export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
export const mod=(x,n)=>((x%n)+n)%n;
export const mix=(a,b,t)=>a+(b-a)*t;
export function edge(h){const x=mod(h,360)/60,f=x%1;return [[1,f,0],[1-f,1,0],[0,1,f],[0,1-f,1],[f,0,1],[1,0,1-f]][Math.floor(x)];}
export function hsv(rgb){const v=Math.max(...rgb),m=Math.min(...rgb),c=v-m;return {h:c?mod((v===rgb[0]?(rgb[1]-rgb[2])/c:v===rgb[1]?2+(rgb[2]-rgb[0])/c:4+(rgb[0]-rgb[1])/c)*60,360):0,s:v?c/v:0,v};}
export const svRgb=(e,s,v)=>e.map(x=>v*(1-s+s*x));
export function sampleSV(data,offset,R,L,n=27){const x=clamp(R,0,26)*(n-1)/26,y=clamp(L,0,26)*(n-1)/26,ix=Math.min(n-2,Math.floor(x)),iy=Math.min(n-2,Math.floor(y)),u=x-ix,v=y-iy;return [0,1].map(c=>{const at=(r,l)=>data[offset+((l*n+r)*2)+c];return mix(mix(at(ix,iy),at(ix+1,iy),u),mix(at(ix,iy+1),at(ix+1,iy+1),u),v);});}
export function nearestSheet(cal,H){H=mod(H,360);const a=cal.rotatedToSheet;let lo=0,hi=a.length;while(lo<hi){let m=(lo+hi)>>1;if(cal.sheetToHue[a[m]]<H)lo=m+1;else hi=m;}const ids=[a[mod(lo-1,a.length)],a[lo%a.length]];return ids.sort((i,j)=>Math.abs(mod(cal.sheetToHue[i]-H+180,360)-180)-Math.abs(mod(cal.sheetToHue[j]-H+180,360)-180))[0];}
export function compactHue(n){if(!Number.isInteger(n)||n<0||n>=6480)throw Error('Hue code is outside the mixed-radix range.');return Math.floor(n/180).toString(36).toUpperCase()+Math.floor(n/5%36).toString(36).toUpperCase()+(n%5);}
export function parseCompactHue(s){if(!/^[0-9A-Z]{2}[0-4]$/.test(s))throw Error('Expected two base-36 hue digits and one base-5 digit.');return parseInt(s[0],36)*180+parseInt(s[1],36)*5+Number(s[2]);}
export function axisCode(v){if(v===26)return 'Z4';if(v<0||v>26)throw Error('R and L must be within 0–26.');const n=Math.floor(v),f=v-n;const sub=Math.abs(f-.8)<1e-7?'X':Math.abs(f*4-Math.round(f*4))<1e-7?String(Math.round(f*4)):null;if(sub===null)throw Error('This coordinate is not a quarter or .8 address.');return String.fromCharCode(65+n)+sub;}
export function parseAxis(s){if(s==='Z4')return 26;if(!/^[A-Z][0-3X]$/.test(s))throw Error('Invalid R/L address field.');return s.charCodeAt(0)-65+(s[1]==='X'?.8:Number(s[1])/4);}
export function compactCode(cal,sheet,R,L,degreeAlias=false){const H=cal.sheetToHue[sheet];let n=4*mod(sheet-cal.startSheet,1530);if(degreeAlias){if(Math.abs(H-Math.round(H))>1e-8)throw Error('This sheet is between whole hue degrees.');n=6120+Math.round(H);}return '$'+compactHue(n)+axisCode(R)+axisCode(L);}
export function decodeCompact(cal,code){const s=code.replace(/^\$/,'').toUpperCase();if(s.length!==7)throw Error('A compact address has seven characters after $.');const n=parseCompactHue(s.slice(0,3));if(n<6120&&n%4!==0)throw Error('This hue index is reserved for future insertions.');const sheet=n>=6120?cal.degreeToSheet[n-6120]:mod(cal.startSheet+n/4,1530);return {sheet,H:cal.sheetToHue[sheet],R:parseAxis(s.slice(3,5)),L:parseAxis(s.slice(5,7))};}
export function directCode({H,R,L}){if(![H,R,L].every(Number.isFinite)||R<0||R>26||L<0||L>26)throw Error('Invalid HRL coordinates.');return '$'+[Math.round(mod(H,360)*2048)%(360*2048),Math.round(R*32768),Math.round(L*32768)].map(x=>x.toString(36).toUpperCase().padStart(4,'0')).join('');}
export function decodeDirect(s){s=s.replace(/^\$/,'').toUpperCase();if(!/^[0-9A-Z]{12}$/.test(s))throw Error('A direct address has twelve base-36 characters after $.');const [h,r,l]=[0,4,8].map(i=>parseInt(s.slice(i,i+4),36));if(h>=360*2048||r>26*32768||l>26*32768)throw Error('Direct address exceeds the HRL coordinate range.');return {H:h/2048,R:r/32768,L:l/32768};}
export async function fetchJSON(url){const r=await fetch(url);if(!r.ok)throw Error(`Could not load ${url} (${r.status}).`);return r.json();}
export async function fetchFloat32(url){const r=await fetch(url);if(!r.ok)throw Error(`Could not load fit data (${r.status}).`);let b=new Uint8Array(await r.arrayBuffer());if(b[0]===31&&b[1]===139)b=new Uint8Array(await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer());return new Float32Array(b.buffer,b.byteOffset,b.byteLength/4);}
export function distances(rgbs,gamut='srgb',weights=[1,1,1]){const pts=rgbs.map(rgb=>coordinatesFromRGB(rgb,{gamut})),series=[[],[],[],[]];for(let i=1;i<pts.length;i++){let squares=[0,0,0];for(let j=0;j<9;j++)squares[Math.floor(j/3)]+=(pts[i][j]-pts[i-1][j])**2;series[0].push(Math.sqrt(squares.reduce((s,v,k)=>s+v*weights[k],0)));[PERIMETERS.sucs,PERIMETERS.gen,PERIMETERS.jzazbz].forEach((p,k)=>series[k+1].push(Math.sqrt(squares[k])*p));}return series;}
export function stats(a){const mean=a.reduce((x,y)=>x+y,0)/Math.max(1,a.length),sd=Math.sqrt(a.reduce((x,y)=>x+(y-mean)**2,0)/Math.max(1,a.length));return {mean,cv:mean>1e-15?sd/mean:0,max:Math.max(0,...a),zero:a.filter(x=>x<1e-12).length};}
